name: Deploy Hugo Site

on:
  push:
    branches:
      - main  # 如果你的主分支叫 master，请改为 master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  # 强制使用 Node.js 24，避免弃用警告
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive  # 必须开启，否则 Stack 主题文件夹会是空的
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true         # Stack 主题依赖 SCSS，必须开启 extended

      - name: Build
        run: hugo --minify

      - name: Deploy to Server
        uses: burnett01/rsync-deployments@v8
        with:
          switches: -avzr --delete
          path: public/
          remote_path: ${{ secrets.REMOTE_TARGET }}
          remote_host: ${{ secrets.SERVER_IP }}
          remote_port: ${{ secrets.REMOTE_PORT }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SERVER_SSH_KEY }}